let questions = [
  {
    numb: 1,
    question: 'Which technology will most influence workplaces in 2025?',
    answer: 'Artificial Intelligence 🤖',
    options: ['Blockchain ⛓️', '3D Printing 🖨️', 'Artificial Intelligence 🤖', 'Quantum Computing ⚛️'],
  },
  {
    numb: 2,
    question: 'Which AI tool is widely used for content generation in 2025?',
    answer: 'ChatGPT 🤖',
    options: ['Photoshop 🖌️', 'ChatGPT 🤖', 'Zoom 🎥', 'Excel 📊'],
  },
  {
    numb: 3,
    question: 'Which skill is considered essential for almost every career?',
    answer: 'Communication 🗣️',
    options: ['Speed reading 📖', 'Drawing ✏️', 'Communication 🗣️', 'Memorization 🧠'],
  },
  {
    numb: 4,
    question: 'Which platform is known for professional networking and resumes?',
    answer: 'LinkedIn 💼',
    options: ['Instagram 📸', 'SnapChat 🫰', 'LinkedIn 💼', 'Facebook 👍'],
  },
  {
    numb: 5,
    question: 'Which tech skill is in high demand across industries?',
    answer: 'AI & Machine Learning 🤖',
    options: ['Data Analytics 📊',
      'AI & Machine Learning 🤖',
      'Cloud Computing ☁️',
      'Cybersecurity 🔒',],
  },
  {
    numb: 6,
    question: 'Best way to structure your daily tasks?',
    answer: 'Prioritize important tasks 😎',
    options: ['Start with random tasks 🌀', 'Rely on memory 🧠', 'Prioritize important tasks 😎', 'Complete only easy tasks 😴'],
  },
  {
    numb: 7,
    question: 'Who is known as the father of computers?',
    answer: 'Charles Babbage 💻',
    options: ['Alan Turing 🤖', 'Charles Babbage 💻', 'Bill Gates 🪟', 'Steve Jobs 🍏'],
  },
  {
    numb: 8,
    question: 'Which approach improves productivity when working remotely?',
    answer: 'Set clear goals 🎯',
    options: ['Switch tasks constantly 🔄', 'Check messages often 📩', 'Set clear goals 🎯', 'Keep email notifications on 🔔'],
  },
  {
    numb: 9,
    question: 'What does “DM” stand for on most social apps?',
    answer: 'Direct Message 📩',
    options: ['Data Monitor 📊', 'Direct Message 📩', 'Digital Media 💻', 'Download Manager 📥'],
  },
  {
    numb: 10,
    question: '5 people paint 5 walls in 5 hours. How many walls can 10 people paint in 10 hours?',
    answer: '20',
    options: ['25', '15', '20', '10'],
  },
];
